import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const rootDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
export const validSlug = slug => /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug);

export function loadConfig(root = rootDirectory) {
  const config = JSON.parse(fs.readFileSync(path.join(root, 'site.config.json'), 'utf8'));
  for (const key of ['name', 'brand', 'symbol', 'language', 'title', 'description', 'footer']) {
    if (typeof config[key] !== 'string' || !config[key].trim()) throw new Error(`site.config.json: ${key} must be nonempty text.`);
  }
  if (typeof config.githubUrl !== 'string' || !config.githubUrl.startsWith('https://github.com/')) throw new Error('githubUrl must be an HTTPS GitHub URL.');
  if (!config.categories || Array.isArray(config.categories) || typeof config.categories !== 'object') throw new Error('Configure blog categories.');
  for (const [id, category] of Object.entries(config.categories)) {
    if (!validSlug(id) || ['main', '__proto__', 'constructor', 'prototype'].includes(id) || !category || typeof category.title !== 'string' || !category.title.trim() || typeof category.description !== 'string') {
      throw new Error(`Invalid blog category: ${id}`);
    }
  }
  if (!Object.hasOwn(config.categories, config.defaultCategory)) throw new Error('defaultCategory must match a configured category.');
  if (!Array.isArray(config.navigation) || !config.navigation.length) throw new Error('Configure navigation links.');
  for (const link of config.navigation) {
    if (!link || typeof link.label !== 'string' || !link.label.trim() || typeof link.href !== 'string' || !/^(?:[a-zA-Z0-9_-]+\/)*[a-zA-Z0-9_.-]*(?:#[a-zA-Z0-9_-]+)?$/.test(link.href) || !link.href || link.href.includes('..')) {
      throw new Error('Navigation links must use local paths, such as index.html#research or blog/.');
    }
  }
  return config;
}

export function page(title, description, prefix, main, config, home = false) {
  const navigation = config.navigation.map(link => {
    const href = home && link.href.startsWith('index.html#') ? link.href.slice('index.html'.length) : prefix + link.href;
    const active = !home && link.href === 'blog/' ? ' aria-current="page"' : '';
    return `      <a href="${escape(href)}"${active}>${escape(link.label)}</a>`;
  }).join('\n');
  return `<!doctype html>
<!-- Generated by npm run build. Edit site.config.json, templates/, or content/posts/. -->
<html lang="${escape(config.language)}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="${escape(description)}">
  <meta name="theme-color" content="#f5f7fa">
  <title>${escape(home ? title : `${title} · ${config.brand}`)}</title>
  <link rel="icon" href="${prefix}favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="${prefix}styles.css">
  ${home ? '<script src="script.js" defer></script>' : ''}
</head>
<body>
  <a class="skip-link" href="#main">Skip to main content</a>
  <header class="site-header">
    <a class="wordmark" href="${home ? '#home' : `${prefix}index.html`}" aria-label="${escape(config.brand)} home"><span class="brand-symbol" aria-hidden="true">${escape(config.symbol)}</span> ${escape(config.brand)}<span class="brand-period">.</span></a>
    <nav aria-label="Main navigation">
${navigation}
    </nav>
  </header>
  <main id="main"${home ? '' : ' class="section-shell blog-main"'}>${main}</main>
  <footer class="site-footer section-shell"><a class="footer-brand" href="${prefix}index.html">${escape(config.brand)}.</a><p>${escape(config.footer)}</p><a href="${escape(config.githubUrl)}" target="_blank" rel="noopener noreferrer">GitHub <span class="sr-only">(opens in a new tab)</span> ↗</a><a href="#main">Back to top ↑</a></footer>
</body>
</html>
`;
}

export function renderHome(root, config) {
  const template = fs.readFileSync(path.join(root, 'templates', 'home.html'), 'utf8');
  const topics = Object.entries(config.categories).map(([id, category], index) => `
        <a href="blog/#${id}"><span class="eyebrow">${String(index + 1).padStart(2, '0')}</span><h3>${escape(category.title)}</h3><p>${escape(category.description)}</p><span class="text-link">View notes →</span></a>`).join('\n');
  const content = template.replaceAll('{{name}}', escape(config.name)).replaceAll('{{blogTopics}}', topics);
  if (/\{\{\w+\}\}/.test(content)) throw new Error('Unknown placeholder in templates/home.html.');
  return page(config.title, config.description, '', content, config, true);
}
